DELETE FROM pendingRareApprovals WHERE id = 'honeybee|graceluna|minecraft:sulfur_cube_bucket|bucket of sulfur cube|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|graceluna|minecraft:sulfur_cube_bucket|bucket of sulfur cube|0|0', 'Bucket of Sulfur Cube', 'minecraft:sulfur_cube_bucket', 0, 0, 0, 1, '1 dia', 1, 8, 8, 'diamond', 'GraceLuna', 'Honeybee', '1573, 85, 618', '2026-09-06T16:41:25.545Z', '2026-09-06T16:44:20.541Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|graceluna|minecraft:cinnabar|cinnabar|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|graceluna|minecraft:cinnabar|cinnabar|0|0', 'Cinnabar', 'minecraft:cinnabar', 0, 0, 0, 2, '2 dia', 64, 1728, 27, 'diamond', 'GraceLuna', 'Honeybee', '1573, 85, 617', '2026-09-06T16:42:12.197Z', '2026-09-06T16:44:20.541Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|trevorcd|minecraft:golden_dandelion|golden dandelion|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|trevorcd|minecraft:golden_dandelion|golden dandelion|0|0', 'Golden Dandelion', 'minecraft:golden_dandelion', 0, 0, 0, 2, '2 dia', 32, 640, 20, 'diamond', 'trevorcd', 'Honeybee', '-3791, 85, -1298', '2026-09-06T18:09:31.339Z', '2026-09-06T18:14:21.272Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|ovrsee|minecraft:cinnabar|cinnabar|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|ovrsee|minecraft:cinnabar|cinnabar|0|0', 'Cinnabar', 'minecraft:cinnabar', 0, 0, 0, 1, '1 dia', 48, 816, 17, 'diamond', 'ovrsee', 'Honeybee', '634, 89, 1051', '2026-09-07T01:21:51.336Z', '2026-09-07T01:32:22.539Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|aslandev|minecraft:cinnabar|cinnabar|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|aslandev|minecraft:cinnabar|cinnabar|0|0', 'Cinnabar', 'minecraft:cinnabar', 0, 0, 0, 1, '1 dia', 64, 1664, 26, 'diamond', 'AslanDev', 'Honeybee', '478, 102, 879', '2026-09-07T08:06:54.111Z', '2026-09-07T08:09:11.755Z', 1)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'firefly|lavenderlyel|minecraft:sulfur_spike|sulfur spike|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('firefly|lavenderlyel|minecraft:sulfur_spike|sulfur spike|0|0', 'Sulfur Spike', 'minecraft:sulfur_spike', 0, 0, 0, 1, '1 dia', 64, 320, 5, 'diamond', 'LavenderlyEl', 'Firefly', '1645, 63, 372', '2026-09-08T12:06:37.187Z', '2026-09-07T15:39:42.202Z', 1)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|aruumi|minecraft:cinnabar|cinnabar|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|aruumi|minecraft:cinnabar|cinnabar|0|0', 'Cinnabar', 'minecraft:cinnabar', 0, 0, 0, 1, '1 dia', 64, 1088, 17, 'diamond', 'aruumi', 'Honeybee', '1173, 75, -3602', '2026-09-08T12:33:54.866Z', '2026-09-07T15:58:00.337Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|aruumi|minecraft:sulfur|sulfur|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|aruumi|minecraft:sulfur|sulfur|0|0', 'Sulfur', 'minecraft:sulfur', 0, 0, 0, 1, '1 dia', 64, 960, 15, 'diamond', 'aruumi', 'Honeybee', '1173, 75, -3603', '2026-09-08T13:24:19.726Z', '2026-09-07T15:58:00.337Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'firefly|thefiirstman|minecraft:sulfur|sulfur|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('firefly|thefiirstman|minecraft:sulfur|sulfur|0|0', 'Sulfur', 'minecraft:sulfur', 0, 0, 0, 1, '1 dia', 64, 384, 6, 'diamond', 'thefiirstman', 'Firefly', '1297, 88, -3846', '2026-09-07T20:23:14.988Z', '2026-09-07T20:34:25.263Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|joneya|minecraft:cinnabar|cinnabar|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|joneya|minecraft:cinnabar|cinnabar|0|0', 'Cinnabar', 'minecraft:cinnabar', 0, 0, 0, 1, '1 dia', 64, 832, 13, 'diamond', 'Joneya', 'Honeybee', '1573, 97, 728', '2026-09-09T06:40:43.049Z', '2026-09-09T06:47:46.611Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|joneya|minecraft:sulfur|sulfur|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|joneya|minecraft:sulfur|sulfur|0|0', 'Sulfur', 'minecraft:sulfur', 0, 0, 0, 1, '1 dia', 64, 192, 3, 'diamond', 'Joneya', 'Honeybee', '1573, 97, 728', '2026-09-09T06:40:43.049Z', '2026-09-09T06:47:46.611Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|joneya|minecraft:sulfur_spike|sulfur spike|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|joneya|minecraft:sulfur_spike|sulfur spike|0|0', 'Sulfur Spike', 'minecraft:sulfur_spike', 0, 0, 0, 1, '1 dia', 15, 58, 3.87, 'diamond', 'Joneya', 'Honeybee', '1573, 97, 728', '2026-09-09T06:40:43.049Z', '2026-09-09T06:47:46.611Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|joneya|minecraft:sulfur_cube_bucket|bucket of sulfur cube|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|joneya|minecraft:sulfur_cube_bucket|bucket of sulfur cube|0|0', 'Bucket of Sulfur Cube', 'minecraft:sulfur_cube_bucket', 0, 0, 0, 1, '1 dia', 1, 2, 2, 'diamond', 'Joneya', 'Honeybee', '1573, 97, 728', '2026-09-09T06:40:43.049Z', '2026-09-09T06:47:46.611Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'honeybee|deafcatrace4|minecraft:sulfur_cube_bucket|bucket of sulfur cube|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('honeybee|deafcatrace4|minecraft:sulfur_cube_bucket|bucket of sulfur cube|0|0', 'Bucket of Sulfur Cube', 'minecraft:sulfur_cube_bucket', 0, 0, 0, 3, '3 dia', 1, 21, 21, 'diamond', 'DEAFCATRACE4', 'Honeybee', '630, 90, 937', '2026-09-09T11:46:07.491Z', '2026-09-09T11:46:32.817Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'firefly|woolu|minecraft:sulfur_bricks|sulfur bricks|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('firefly|woolu|minecraft:sulfur_bricks|sulfur bricks|0|0', 'Sulfur Bricks', 'minecraft:sulfur_bricks', 0, 0, 0, 2, '2 dia', 64, 704, 11, 'diamond', 'Woolu', 'Firefly', '-3956, 49, -706', '2026-09-09T13:50:38.543Z', '2026-09-09T14:02:24.580Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
DELETE FROM pendingRareApprovals WHERE id = 'firefly|woolu|minecraft:sulfur|sulfur|0|0';
INSERT INTO listings (rowKey, itemName, baseItem, bulk, bundled, mixedContents, price, priceLabel, stackSize, amount, stacksInStock, currency, seller, world, position, lastSeen, availableSince, missingStreak)
VALUES ('firefly|woolu|minecraft:sulfur|sulfur|0|0', 'Sulfur', 'minecraft:sulfur', 0, 0, 0, 2, '2 dia', 64, 1728, 27, 'diamond', 'Woolu', 'Firefly', '-3954, 49, -706', '2026-09-09T13:50:39.293Z', '2026-09-09T14:02:24.580Z', 0)
ON CONFLICT(rowKey) DO UPDATE SET itemName=excluded.itemName, baseItem=excluded.baseItem, bulk=excluded.bulk, bundled=excluded.bundled, mixedContents=excluded.mixedContents, price=excluded.price, priceLabel=excluded.priceLabel, stackSize=excluded.stackSize, amount=excluded.amount, stacksInStock=excluded.stacksInStock, currency=excluded.currency, seller=excluded.seller, world=excluded.world, position=excluded.position, lastSeen=excluded.lastSeen, missingStreak=excluded.missingStreak;
